<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SmartCert - Home</title>
    <style>
        body {
            background-color: #011029; 
            color: white; 
            font-family: Arial, sans-serif;
        }
        button {
            background-color: #094CAD; 
            color: white; 
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
        }
        button:hover {
            background-color: #083A8A; 
        }
    </style>
</head>
<body>
    <button 
        onclick="window.location.href='/logout'">
        Logout
    </button>
</body>
</html>