<!DOCTYPE html>
<html lang="pt-br" class="scroll-smooth">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Smart Cert</title>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <script src="/assets/js/application.js"></script>

        <script src="https://cdn.tailwindcss.com"></script>
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet" />
        
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <link rel="stylesheet" href="/assets/css/application.css">
        
        <style>
            body {
                font-family: "Inter", sans-serif;
            }
        </style>
    </head>

    <body class="bg-[#0B1636] text-white min-h-screen flex flex-col">
        <header class="flex justify-between items-center px-6 py-4 border-b border-[#14254E]">
            <div class="font-semibold text-lg text-[#4A90E2]">SmartCert</div>
            <nav class="space-x-6 text-white text-base font-normal">
                <a href="#" class="hover:underline hover:text-[#4A90E2] transition-colors">Perfil</a>
                <a href="logout" class="hover:underline hover:text-[#4A90E2] transition-colors">Logout</a>
            </nav>
        </header>

        <main class="flex-grow p-6">
            <?php require '_flash_message.phtml'; ?>
            
            <?php require $view ?>
        </main>
    </body>
</html>